export type Bindings = {
	GROQ_API_KEY: string
	TURSO_DATABASE_URL: string
	TURSO_AUTH_TOKEN: string
	SENTRY_DSN: string
	WHATSAPP_VERIFY_TOKEN: string
	WHATSAPP_PHONE_NUMBER_ID: string
	WHATSAPP_ACCESS_TOKEN: string
	WHATSAPP_GRAPH_API_VERSION?: string
	DASHBOARD_URL?: string
	CLERK_PUBLISHABLE_KEY?: string
	CLERK_SECRET_KEY?: string
}
